### ISSUE TITLE
Question: How to handle here-document

### ISSUE THREAD

**Issue by skaji** [charsbar/Parse-PMFile#10]
This is not a bug report, but a question.

In the following code, I expect Example.pm does not provide `InnerHereDoc` package, but Parse-PMFile (or PAUSE?) reports Example.pm provides `InnerHereDoc` package.

So the question is:
If pm files have here-document that may have "package Hogehoge" lines,
then do module authors need to take care of it themselves?

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use Parse::PMFile;

my $pmfile = "Example.pm";

open my $fh, ">", $pmfile or die;
print {$fh} <DATA>;
close $fh;
close DATA;

my $parser = Parse::PMFile->new;
my $info = $parser->parse($pmfile);

use Data::Dumper;
print Dumper $info;

__DATA__

package Example;

my $heredoc = <<EOF;
package InnerHereDoc;
EOF
```
```
❯ perl test.pl
$VAR1 = {
          'Example' => {
                         'parsed' => 1,
                         'filemtime' => 1520636693,
                         'infile' => 'Example.pm',
                         'simile' => 'Example.pm',
                         'version' => 'undef'
                       },
          'InnerHereDoc' => {
                              'version' => 'undef',
                              'infile' => 'Example.pm',
                              'filemtime' => 1520636693,
                              'parsed' => 1
                            }
        };
```

**Comment by charsbar** [comment]
Generally speaking, PAUSE (and thus Parse::PMFile) doesn't try hard to exclude weird stuff now, because it's pretty difficult to parse everything correctly. If a module author does something clever, it's up to the author to provide a correct set of ```provides``` (or maybe ```no_index```) in META files, or add a bit more cleverness to hide such cleverness from PAUSE (like adding a newline, or concatenating strings, or replace the package name with a variable, etc). It's much easier for the author to tell what's going wrong, than for us.

That being said, I'm hoping someday we can use a better detector enough to convince Andreas or maybe p5p. It might be Module::Metadata, or an improved version of Parse::PMFile, or maybe a bit more compact version of Perl::PrereqScanner::NotQuiteLite (ie. something compact enough for other tools like cpm/cpanminus to use) . 

I close this issue, but feel free to continue if you want.
